spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
  mvc:
    favicon:
      enabled: false
server:
  port: 9090
  servlet:
    context-path: /app